#!/bin/bash
PATH="$PATH:/etc/VeilerTools/usr/bin/"
PKGREPO="https://ilovetrees242.github.io/DevHelp/Website/Packages/"
VEILERTESTS=0
VEILERQUIET=0
VEILERDOC=0
VEILERASK=0
YELLOW='\033[1;33m'
ORANGE='\033[0;33m'
WHITE='\033[1;37m'
GRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
NC='\033[0m'

PROCESSID=""
VEILERARGS=""

package_check(){
    if [ $(id -u) != 0 ]; then
        echo -e "${ORANGE}You are not root! run as root with: ${WHITE}sudo ${YELLOW}$0${NC}"
        exit 1
    fi
    while true; do
        printf "\r${ORANGE}Checking if required packages are installed on your computer   ${NC}"; sleep 0.2
        printf "\r${ORANGE}Checking if required packages are installed on your computer.  ${NC}"; sleep 0.2
        printf "\r${ORANGE}Checking if required packages are installed on your computer.. ${NC}"; sleep 0.2
        printf "\r${ORANGE}Checking if required packages are installed on your computer...${NC}"; sleep 0.2
    done &
    PROCESSID=$!
    for PACKAGE in find bash wget awk gcc make patch grep tar readelf; do
        $PACKAGE --version &> /dev/null 
        if [ $? -eq 127 ]; then
            echo -e "${YELLOW}$PACKAGE is not installed on your system! Veiler will use prebuilt binaries from the tool directory.${NC}"
            PATH=$PATH:/usr/lib/Veiler/Tools/usr/bin/
        fi
        sleep 0.1
    done && kill $PROCESSID && printf "\n${YELLOW}Done!${NC}\n"     
}
clean(){
    for directory in $(find /var/cache/Veiler/ -type d | sed '1d'); do
        rm -rfv "$i"
    done
}
uninstalldb(){
    LINENUMBER="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
    sed -i "${LINENUMBER} s@yes@no@" /var/db/Veiler/package.db
}
installdb(){
    LINENUMBER="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
    sed -i "${LINENUMBER} s@no@yes@" /var/db/Veiler/package.db
}
for(( i=1; i <= $#; i++ )){
    case ${!i} in
        --quiet)
            if [ $VEILERQUIET -eq 0 ]; then
                set -- ${@:1:$((i-1))} ${@:$((i+1))}
                VEILERQUIET=1
                i=0
            elif [ $VEILERQUIET -eq 1 ]; then
                echo -e "${Yellow}Quiet mode already enabled!${NC}"; exit 1
            fi
        ;;
        --documentation)
            if [ $VEILERDOC -eq 0 ]; then 
                set -- ${@:1:$((i-1))} ${@:$((i+1))}
                VEILERDOC=1
                i=0
            elif [ $VEILERDOC -eq 1 ]; then
                echo -e "${YELLOW}Documentation already enabled!${NC}"; exit 1
            fi
        ;;
        --tests)
            if [ $VEILERTESTS -eq 0 ]; then
                set -- ${@:1:$((i-1))} ${@:$((i+1))}
                VEILERTESTS=1
                i=0
            elif [ $VEILERTESTS -eq 1 ]; then
                echo -e "${YELLOW}Tests are already enabled!${NC}"; exit 1
            fi
        ;;
        --ask)
            if [ $VEILERASK -eq 0 ]; then
                set -- ${@:1:$((i-1))} ${@:$((i+1))}
                VEILERASK=1
                i=0
            elif [ $VEILERASK -eq 0 ]; then
                echo -e "${YELLOW}Confirmation prompts are already enabled!${NC}"; exit 1
            fi
    esac
}
case $1 in
	unveil)
        package_check
        if [ -z "$2" ]; then
            echo -e "${YELLOW}Package name not specified!${NC}"
            exit 1
        fi
        shift 
        if [ $VEILERQUIET -eq 0 ]; then
            if [ $# -ge 2 ]; then
                VEILERARGS=$@
                for(( i=0; i < $#; i++ )){
                    echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
                    cd /var/cache/Veiler && clean
                    PREVUSERPWD=$PWD
                    echo -e "${YELLOW}Checking if packages exist...${NC}"
                    wget $PKGREPO$1.tar.gz 
                    if [ $? -eq 0 ]; then
                        echo -e "${YELLOW}->Package ${WHITE}$1 ${YELLOW} found${NC}"
                    elif [ $? -eq 8 ]; then
                        echo -e "${YELLOW}->Package ${ORANGE}$1${YELLOW} not found!${NC}"
                        exit 1
                    else
                        echo -e "${YELLOW}->An unknown error occured while fetching the packages.${NC}"
                        exit 1
                    fi
                }
                set -- $VEILERARGS
                # TO DO: loop for extracting and building each package one by one
                    # xxx
            else
                echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
                pushd /var/cache/Veiler && clean
                echo -e "${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists...${NC}"
                if [ ! -f $1.tar.gz ]; then
                    wget "$PKGREPO$1.tar.gz"   
                fi
                case $? in 
                    8)
                        echo -e "${YELLOW}Package ${ORANGE}$1${YELLOW} not found!${NC}"
                        exit 1
                    ;;
                    0)
                        echo -e "\n${ORANGE}Package ${WHITE}$1${ORANGE} found!${NC}"
                        if [ $VEILERASK -eq 1 ]; then
                            echo -ne "${WHITE}Proceed with the installation?[y/n]: ";  
                            read -n 1 
                            if [ $REPLY == "n" ]; then
                                echo -e "\n${YELLOW}Ok.${NC}"; exit 0
                            fi
                            if [[ $REPLY != "y" && $REPLY != "n" ]]; then
                                echo -e "\n${YELLOW}Not a valid choice!${NC}"; exit 1
                            fi
                        fi
				        echo -e "\n${YELLOW}Installing ${WHITE}$1${YELLOW} in${NC}"
				        for i in 1 2 3 4 5 ; do
                            printf "${WHITE}%d${NC}" "$i"
					        for j in 1 2 3; do
                                sleep 0.1
                                printf "${YELLOW}.${NC}"
                            done
                            sleep 1
				        done
                        echo
                        echo -e "${YELLOW}Extracting the build tarball...${NC}"
                        tar xvf $1.tar.gz
                        pushd $1
                            source ./MOONBUILD chkdeps
                            source ./MOONBUILD build
                            source ./MOONBUILD install 
                            installdb $1
                            VERLINE="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
                            sed -i "${VERLINE} s@0@${MOONPKGVERSION}@" /var/db/Veiler/package.db
                            trap - ERR
                        popd
                    ;;
                    *)
                        echo -e "${YELLOW}An unknown error was encountered while downloading the build tarball.${NC}"
                        popd
                        exit 1
                    ;;
                esac
                popd
            fi
        elif [ $VEILERQUIET -eq 1 ]; then
            echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
            pushd /var/cache/Veiler &> /dev/null && clean &> /dev/null
            if [ $# -ge 2 ]; then
                # TO DO: Add commands for fetching and building multiple packages
                echo "DEBUG : $@"
            else
                while true; do
                    echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists   ${NC}"; sleep 0.2; 
                    echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists.  ${NC}"; sleep 0.2; 
                    echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists.. ${NC}"; sleep 0.2; 
                    echo -ne "\r${ORANGE}Checking if package ${YELLOW}$1${ORANGE} exists...${NC}"; sleep 0.2; 
                done &
                PROCESSID=$!
	    	    wget "$PKGREPO$1.tar.gz" &> /dev/null
                case $? in
		    	    8)
                        kill $PROCESSID
			    	    echo -e "${YELLOW}Package ${ORANGE}$1${YELLOW}not found!${NC}"
                        exit 1
                    ;;
			        0)  
                        kill $PROCESSID
                        echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
                        if [ $VEILERASK -eq 1 ]; then
                            echo -ne "${WHITE}Proceed with the installation?[y/n]: ";  
                            read -n 1 
                            if [ $REPLY == "n" ]; then
                                echo -e "\n${YELLOW}Ok.${NC}"; exit 0
                            fi
                            if [[ $REPLY != "y" && $REPLY != "n" ]]; then
                                echo -e "\n${YELLOW}Not a valid choice!${NC}"; exit 1
                            fi
                        fi
				        echo -e "\n${YELLOW}Installing ${WHITE}$1${YELLOW} in${NC}"
				        for i in 1 2 3 4 5 ; do
                            printf "${WHITE}%d${NC}" "$i"
					        for j in 1 2 3; do
                                sleep 0.1
                                printf "${YELLOW}.${NC}"
                            done
                            sleep 1
				        done
                        echo
                        trap 'echo -e "${ORANGE}Could not extract the build tarball.${NC}; kill $PROCESSID; exit 1;"' ERR
                        while true; do
                            echo -ne "\r${ORANGE}Extracting the build tarball   ${NC}"; sleep 0.2; 
                            echo -ne "\r${ORANGE}Extracting the build tarball.  ${NC}"; sleep 0.2; 
                            echo -ne "\r${ORANGE}Extracting the build tarball.. ${NC}"; sleep 0.2; 
                            echo -ne "\r${ORANGE}Extracting the build tarball...${NC}"; sleep 0.2; 
                        done &
                        PROCESSID="$!"
                        tar xf $1.tar.gz 
                        if [ $? -ne 0 ]; then echo -e "${ORANGE}An error was encountered while extracting the build tarball${NC}"; exit 1; kill $PROCESSID; fi
                        kill $PROCESSID; echo -e "\n${YELLOW}Successfully extracted the build tarball!${NC}"
		    		    pushd "$1" &> /dev/null
                            source ./MOONBUILD chkdeps
			    	        source ./MOONBUILD build
                            source ./MOONBUILD install
                            installdb $1
                            VERLINE="$(cat -n /var/db/Veiler/package.db | grep $1 | awk '{print $1}')"
                            sed -i "${VERLINE} s@$(cat /var/db/Veiler/package.db | grep $1 | awk '{print $3}')@$MOONPKGVERSION@" /var/db/Veiler/package.db
			            popd &> /dev/null
                        rm -rf "$1"
				    ;;
                    *)
                        echo -e "${YELLOW}An unknown error occured. Manual intervention is required. Please use verbose mode and inspect the package manager script manually.${NC}"
                        exit 1
                    ;;
		        esac
                popd
            fi
        fi
    ;;
	veil)
        package_check
        if [ -z "$2" ]; then
            echo -e "${YELLOW}Package name not specified!${NC}"
            exit 1
        fi
        shift
        if [ "$VEILERQUIET" -eq 1 ]; then
            echo -e "${YELLOW}Changing directory to /var/cache/Veiler...${NC}"
            pushd /var/cache/Veiler &> /dev/null && clean &> /dev/null
            if [ $# -ge 2 ]; then
                echo "\033[s"
                while true; do
                    echo -ne "\r${ORANGE}Checking if packages exist   ${NC}"; sleep 0.2; echo "\033[u"
                    echo -ne "\r${ORANGE}Checking if packages exist.  ${NC}"; sleep 0.2; echo "\033[u"
                    echo -ne "\r${ORANGE}Checking if packages exist.. ${NC}"; sleep 0.2; echo "\033[u"
                    echo -ne "\r${ORANGE}Checking if packages exist...${NC}"; sleep 0.2; echo "\033[u"
                done &
                PROCESSID=$!
                wget "$PKGREPO$1.tar.gz" &> /dev/null 
                if [ $? -eq 8 ]; then
                    echo -e "${YELLOW}Package $1 not found!${NC}"
                elif [ $? -eq 0 ]; then
                    echo -e "${WHITE}->${YELLOW}Package ${WHITE}$1${YELLOW} found${NC}"
                else
                    echo -e "${YELLOW}An unknown error was encountered while checking if packages exist. Manual intervention required.${NC}"
                fi
            else
                while true; do
		            echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists   ${NC}"; sleep 0.2
		            echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists.  ${NC}"; sleep 0.2
		            echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists.. ${NC}"; sleep 0.2
		            echo -ne "\r${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists...${NC}"; sleep 0.2
                done &
                PROCESSID=$!
		        wget "$PKGREPO$1.tar.gz" &> /dev/null && kill $PROCESSID && echo
		        case $? in
		            8)
				        echo -e "${YELLOW}Package ${WHITE}$1${WHITE}does not exist!${NC}"
                        kill $PROCESSID
		    	    ;;
                    0)
                    echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
                    echo -e "${YELLOW}Checking if its already uninstalled...${NC}"
                    if [ $(cat /var/db/Veiler/package.db | grep $1 | awk '{print $2}') == "no" ]; then
                        echo -e "${WHITE}The package ${YELLOW}$1${WHITE} is already uninstalled.${NC}"
                        exit 1
                    else
                        echo -e "${WHITE}Ok. The package ${YELLOW}$1${WHITE} is going to be uninstalled.${NC}"
                        if [ $VEILERASK -eq 1 ]; then
                            echo -ne "${WHITE}Proceed with the uninstallation?[y/n]${NC}"
                            read -n 1
                            if [ $REPLY == "n" ]; then
                                echo -e "\n${YELLOW}Ok."
                                exit 0
                            fi
                            if [[ $REPLY != "n" && $REPLY != "y" ]]; then
                                echo -e "\n${YELLOW}Please enter a valid choice."
                                exit 1
                            fi
                        fi
                    fi
			        echo -e "${YELLOW}Uninstalling ${WHITE}$1${YELLOW} in${NC}"
			        for i in 1 2 3 4 5 ; do
                        printf "${WHITE}%d${NC}" "$i"
			            for j in 1 2 3; do
                            sleep 0.1
                            printf "${YELLOW}.${NC}"
                        done
                        sleep 1
			        done
                    echo
                    while true; do
                        echo -ne "\r${ORANGE}Extracting the build tarball   ${NC}"; sleep 0.2
                        echo -ne "\r${ORANGE}Extracting the build tarball.  ${NC}"; sleep 0.2
                        echo -ne "\r${ORANGE}Extracting the build tarball.. ${NC}"; sleep 0.2
                        echo -ne "\r${ORANGE}Extracting the build tarball...${NC}"; sleep 0.2
                    done &
                    PROCESSID=$!
                    tar xf "$1.tar.gz" && kill $PROCESSID && echo -e "\n${YELLOW}->Successfully extracted $1.tar.gz${NC}"
                    if [ $? -ne 0 ]; then echo -e "${ORANGE}An error was encountered while extracting!${NC}"; kill $PROCESSID; exit 1; fi
					pushd "$1" &> /dev/null
				        source ./MOONBUILD uninstall
                        uninstalldb $1
				    popd &> /dev/null
			        ;;
                    *)
                        echo -e "${YELLOW}An unknown error has been encountered. Manual intervention is required.${NC}"
                        popd &> /dev/null
                        exit 1
                    ;;
		        esac
            popd &> /dev/null
            fi
        else
            echo -e "${YELLOW}Changing directory to /var/cache/Veiler..."; sleep 2
            pushd /var/cache/Veiler && clean
            if [ $# -ge 2 ]; then
                # TO DO : Build commands for multiple packages
                xx
            else
                echo -e "${ORANGE}Checking if the package ${YELLOW}$1${ORANGE} exists...${NC}"; sleep 0.2
                PROCESSID="$!"
                wget $PKGREPO$1.tar.gz
                case $? in 
                    8)
                        echo -e "${YELLOW}Package ${WHITE}$1${YELLOW} does not exist!${NC}"
                        exit 1
                    ;;                    
                    0)
                        echo -e "\n${ORANGE}Package ${WHITE}$1${WHITE} found!${NC}"
                        if [ $(cat /var/db/Veiler/package.db | grep $1 | awk '{print $2}') == "no" ]; then
                            echo -e "${WHITE}The package ${YELLOW}$1${WHITE} is already uninstalled.${NC}"
                            exit 1
                        fi
    			        echo -e "${YELLOW}Uninstalling ${WHITE}$1${YELLOW} in${NC}"
	    		        for i in 1 2 3 4 5 ; do
                            printf "${WHITE}%d${NC}" "$i"
			                for j in 1 2 3; do
                                sleep 0.1
                                printf "${YELLOW}.${NC}"
                            done
                        sleep 1
			            done
                        echo
                        printf "${YELLOW}Extracting the build tarball now...${NC}"
                        tar xvf "$1.tar.gz"
                        if [ $? -ne 0 ]; then echo -e "${ORANGE}An error was encountered while extracting!${NC}"; exit 1; fi
                        pushd "$1"
                            source ./MOONBUILD uninstall
                            uninstalldb $1
                        popd
                    ;;
                    *)
                        echo -e "${ORANGE}An unknown error was encountered while downloading the build tarball.${NC}"
                        exit 1
                esac
            fi
         fi
	;;
	strengthen)
        # TO DO: Later, add a feature to update packages installed on system if new version has been released and is greater than installed version
        xx
	;;
    info)
        if [ -z $2 ]; then
            echo -e "${YELLOW}No package provided.${NC}"
        fi
        OUT="$(sudo cat /var/db/Veiler/package.db | grep $2 | head -n1 | tail -n1)"
        if [ -z "$OUT" ]; then
            echo -e "${WHITE}Package ${YELLOW}$2 ${WHITE}does not exist!${NC}"
        else
            echo -e "${WHITE}$OUT${NC}"
        fi
    ;;
	help)
		echo -e "${YELLOW}$0 Usage: $0 <OPTIONS> <COMMAND>${NC}"
		echo -e "${WHITE}$0 unveil|veil <OPTIONS> [PACKAGE]${NC}"
		echo -e "${WHITE}$0 Options:" 
	   echo -e "${GRAY}--verbose${NC}${WHITE} : Displays verbose output${NC}"
       echo -e "${GRAY}--quiet${NC}${WHITE} : Displays quiet output, not too detailed.${NC}"
	   echo -e "${GRAY}--documentation${NC}${WHITE} : Enables documentation (this might install extra dependencies)${NC}"
	   echo -e "${GRAY}--test${NC}${WHITE}: Enables test harnesses${NC}" 
       echo -e "${GRAY}--ask${NC}${WHITE}: Use confirmation prompts before performing actions related to the entire package${NC}"
		echo -e "${WHITE}$0 unveil: Installs a package from source.${NC}"
		echo -e "${WHITE}$0 veil  : Uninstalls a package installed on the system${NC}"
		echo -e "${WHITE}$0 strengthen: Updates all packages installed on the system${NC}"
		echo -e "${WHITE}$0 help: Displays this output${NC}"
        echo -e "${WHITE}$0 version: Display package manager version${NC}"
        echo -e "${WHITE}$0 info: Display information about a package${NC}"
		
	;;
    version)
            echo -e "Veiler development version. r0-1"
    ;;
	*)
        echo -e "${WHITE}Invalid action ${YELLOW}$1${WHITE} specified!${NC}"
        $0 help
	;;
esac
