#!/bin/bash

# Colors
DARKBLUE='\033[0;34m'
BLUE='\033[1;34m'
RED='\033[1;31m'
YELLOW='\033[1;33m'
ORANGE='\033[0;33m'
WHITE='\033[1;37m'
GRAY='\033[0;37m'
DARKGRAY='\033[1;30m'
NC='\033[0m'

log_warn(){
    echo -e "${ORANGE}WARNING >>>${WHITE} $1${NC}"
}
log_err(){
    if [ "$1" == "noexit" ];then 
        echo -e "${RED}ERROR >>>${WHITE} $2${NC}"
    else
        echo -e "${RED}ERROR >>>${WHITE} $1${NC}"
        exit 1
    fi
    shift
}
log_info(){
    case $1 in
        tip)
            echo -e "${BLUE}Tip >>>${WHITE} $2${NC}"
        ;;
        imp)
            echo -e "${YELLOW}Important >>>${WHITE} $2${NC}"    
        ;;
        notice)
            echo -e "${YELLOW}Notice >>>${WHITE} $2${NC}"    
        ;;
        activity)
            echo -e "${YELLOW}Activity >>>${WHITE} $2${NC}"    
        ;;
    esac
}
VEILERCUSTOMCONF=0
while [ $# -gt 0 ]; do
    case $1 in 
        --*)
            OPTIONS+=($1)
            case $1 in
                --with-dest)
                    if [ -n $2 ]; then
                        OPTIONS+=($2); shift
                    else
                        log_err "The option ${GRAY}--with-dest${WHITE} requires an argument!"
                    fi
                ;;
                --config)
                    if [ -z $2 ]; then
                        log_err "The option ${GRAY}--config${WHITE} requires a valid argument!"
                    elif [ $(echo $2 | cut -c1) != "/" ]; then
                        log_err "The option ${GRAY}--config${WHITE} requires an absolute path!"
                    elif [ ! -f $2 ]; then
                        log_err "Requested configuration file: ${YELLOW}$2${WHITE} does not exist on the system."
                    fi
                    OPTIONS+=($2); shift
                ;;
            esac
        ;;
        *)
            ARGUMENTS+=($1)
        ;;
    esac
    shift
done
for((i=0; i < ${#OPTIONS[@]}; i++)){
    if [ "${OPTIONS[$i]}" == "--config" -a -s $VEILERCONFIGPATH ]; then
        VEILERCONFIGPATH=${OPTIONS[$((i+1))]}
        VEILERCUSTOMCONF=1
        log_info notice "Using $VEILERCONFIGPATH as config"
    fi
}
# Main package manager related variables
declare -a OPTIONS PACKAGES
VEILERTESTS=0
VEILERQUIET=0
VEILERDOC=0
VEILERASK=0
VEILERONLYBUILD=0
VEILERNOROOT=0
VEILERSKIPDESC=0
VEILERSKIPDEPS=0
VEILERSKIPCLEAN=0
VEILERSKIPINST=0
VEILERSKIPINTEGRITY=0
VEILERERREXIT=0
VEILERMBE=0
VEILERDEST="/"
VEILERCACHEPATH="/var/cache/Veiler/"
VEILERDBPATH="/var/db/Veiler"
VEILERPREFIX="/usr"
PROCESSID=""
PKGREPO="https://ilovetrees242.github.io/Supplements/Website/Packages"
USEFLAGS=""
GLOBALUSEFLAGS=()
LOCALUSEFLAGS=()
STACK=()

if [ $VEILERCUSTOMCONF -eq 0 -a -s $VEILERCONFIGPATH ]; then 
    . /etc/Veiler/veiler.conf
elif [ $VEILERCUSTOMCONF -eq 1 ]; then 
    . $VEILERCONFIGPATH
fi

# Package handling related variables
declare -a PKGNAME PKGVERSION
declare -A visited
PACKAGES=()
RESOLVEPACKAGES=()
DEPS=()
PKGNAME=()
PKGVERSION=()

ADDITIONALDEPS=()
UPGRADEDPACKAGES=()
UPGRADEDPACKAGESLOCALVERSION=()
UPGRADEDPACKAGESSYNCVERSION=()
LOCALPKGVERSIONS=()
SYNCPKGVERSIONS=()

# Space and size related variables
TOTALDSR=0
TOTALINSTSIZE=0
TOTALUNINSTSIZE=0
TOTALDOWNLOADSIZE=0
TOTALUPGRADESIZE=0
TOTALUPGRADESIZEWODOC=0
WODOCINSTSIZE=0
SIZEBUFFER=0

# Extra variables

TRAPSET=0

if [ $(echo $VEILERDEST | cut -c1) != "/" ]; then
    log_err "DEST path must be an absolute path."
elif [ $(echo $VEILERCACHEPATH | cut -c1) != "/" ]; then
    log_err "Cache path must be absolute."
elif [ $(echo $VEILERDBPATH | cut -c1) != "/" ]; then
    log_err "DB path must be absolute."
fi

trap 'veiler_stop_animation' TERM 
trap 'echo -e "\n${YELLOW}Interrupted${NC}"; veiler_stop_animation; exit 1' INT

# --- Functions ---
play_animation(){
    while true; do
        printf "\r$1${WHITE}   ${NC}"; sleep 0.1
        printf "\r$1${WHITE}.  ${NC}"; sleep 0.1
        printf "\r$1${WHITE}.. ${NC}"; sleep 0.1
        printf "\r$1${WHITE}...${NC}"; sleep 0.1
    done &
    PROCESSID=$!
}
second_animation(){
    while true; do
        printf "\r$1${WHITE} [/]${NC}"; sleep 0.2
        printf "\r$1${WHITE} [-]${NC}"; sleep 0.2
        printf "\r$1${WHITE} [\\]${NC}"; sleep 0.2
        printf "\r$1${WHITE} [-]${NC}"; sleep 0.2
    done &
    PROCESSID=$!
}
veiler_stop_animation(){
    if [ -n "$PROCESSID" ]; then kill "$PROCESSID" &> /dev/null; echo; fi
}
clean(){
    if [ $VEILERSKIPCLEAN -eq 0 -a -d $VEILERCACHEPATH ]; then
        for directory in $(find $VEILERCACHEPATH -type d | sed '1d'); do
            rm -rf "${directory}" || log_err "Could not clean cache!"
        done        
    else
        return
    fi
}
checkifroot(){
    if [ $VEILERNOROOT -eq 0 -a $(id -u) -ne 0 ]; then
        log_err "You have to become root to perform this action."
    fi
}
checkIfAlreadyInstalled(){
    declare -a local newPackages
    newPackages=()
    for PACKAGE in $@; do
        if [ ! -d "$VEILERDBPATH/local/$PACKAGE" ]; then
            newPackages+=( $PACKAGE )
        fi
    done
    echo ${newPackages[@]}
}
getBuildTarballs(){
    log_info imp "Fetching package(s)..."
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        if [ ! -f "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz" ]; then
            if [ $VEILERQUIET -eq 0 ]; then 
                wget -nv --show-progress "$PKGREPO"/build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz
            else 
                wget -q --show-progress "$PKGREPO"/build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz
            fi
            if [ $? -ne 0 ]; then 
                log_err noexit "Could not download the package ${YELLOW}${PKGNAME[$i]}${WHITE}!" && log_info tip "Maybe try running $0 ${GRAY}sync?${NC}"
                exit 1
            fi
        fi
        source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
        unset MOONPKGNAME MOONPKGVERSION DESC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
        if [ -n "$MOONBASEPKG" ]; then
            source $VEILERDBPATH/sync/$MOONBASEPKG/info
            unset MOONPKG DESC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
            log_info notice "Downloading the base package >>> ${BLUE}$MOONBASEPKG${WHITE} for ${BLUE}${PKGNAME[$i]}"
            if [ ! -f "build-$MOONPKGNAME-$MOONPKGVERSION.tar.gz" ]; then
                wget -nv --show-progress "$PKGREPO/build-$MOONPKGNAME-$MOONPKGVERSION.tar.gz"
            fi
        fi
    }
}
extractBuildTarballs(){
    log_info imp "Extracting the package build tarball(s)..."
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Extracting ${YELLOW}>>> ${WHITE}${PKGNAME[$i]}${NC}"
        if [ $VEILERNOROOT -eq 0 ]; then
            su -c "if [ $VEILERQUIET -eq 1 ]; then tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"; else tar xvf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"; fi" veiler-build-user
        else
            if [ $VEILERQUIET -eq 1 ]; then tar xf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"; else tar xvf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz"; fi
        fi
        source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
        unset MOONPKG DESC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE MOONPKGNAME MOONPKGVERSION 
        if [ -n "$MOONBASEPKG" ]; then
            source $VEILERDBPATH/sync/$MOONBASEPKG/info
            unset MOONPKG DESC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE
            if [ $VEILERNOROOT -eq 0 ]; then
                su -c "if [ $VEILERQUIET -eq 1 ]; then tar xf "build-"$MOONPKGNAME"-"$MOONPKGVERSION".tar.gz"; else tar xvf "build-"$MOONPKGNAME"-"$MOONPKGVERSION".tar.gz"; fi" veiler-build-user
            else
                if [ $VEILERQUIET -eq 1 ]; then tar xf "build-"$MOONPKGNAME"-"$MOONPKGVERSION".tar.gz"; else tar xvf "build-"$MOONPKGNAME"-"$MOONPKGVERSION".tar.gz"; fi
            fi
        fi
        if [ $? -ne 0 ]; then
            log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Could not extract the build tarball for ${RED}>>> ${WHITE}${PKGNAME[$i]}"
        fi
    }
}
getSources(){
    log_info imp "Getting source(s) [ ${YELLOW}${#PKGNAME[@]}${WHITE} ]..."
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            unset MOONPKGNAME MOONPKGVERSION DESC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
            if [ -n "$MOONBASEPKG" ]; then
                source $VEILERDBPATH/sync/$MOONBASEPKG/info
                if [ -z "$EXTENSION" ]; then
                    log_err noexit "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Valid extension could not be found for base package${RED} >>> ${WHITE}$MOONPKGNAME"
                    log_info tip "Extensions for the source tarball. Example: acl-2.3.2.tar.xz - extension = .tar.xz. More valid extensions for compressed files: .zip, .tar.zst, .tar.gz, .bzip2"
                    exit 1
                fi
                cd ../build-$MOONPKGNAME-$MOONPKGVERSION
            fi
            if [ -z "$EXTENSION" ]; then
                log_err noexit "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Valid extension could not be found for ${PKGNAME[$i]}"
                log_info tip "Extensions for the source tarball. Example: acl-2.3.2.tar.xz - extension = .tar.xz. More valid extensions for compressed files: .zip, .tar.zst, .tar.gz, .bzip2"
                exit 1
            fi
            if [ -n "$SRC" ]; then
                if [ ! -f "$MOONPKG$EXTENSION" ]; then
                    if [ $VEILERQUIET -eq 0 ]; then
                        wget -nv "$SRC" -O "$MOONPKG$EXTENSION"
                    else
                        wget -q --show-progress "$SRC" -O "$MOONPKG$EXTENSION"
                    fi
                fi
                if [ $? -ne 0 ]; then
                    log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to download the source for ${PKGNAME[$i]}"
                fi
            else
                if [ $VEILERERREXIT -eq 0 ]; then
                    log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Valid source could not be found for ${PKGNAME[$i]}"
                fi
            fi      
            unset MOONBASEPKG
            if [ -s $VEILERDBPATH/sync/${PKGNAME[$i]}/additionaldownloads ]; then
                log_info imp "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Downloading additional files for the package ${BLUE}>>>${WHITE} ${PKGNAME[$i]} ${BLUE}<<< $(wc -l $VEILERDBPATH/sync/${PKGNAME[$i]}/additionaldownloads | sed 's/\s.*//')"
                while read filename; do
                    if [ ! -f "$(echo $filename | sed 's/.*\///')" ]; then
                       if [ $VEILERQUIET -eq 1 ]; then
                           wget -q --show-progress $filename
                       else
                           wget -nv --input-file $filename
                       fi
                    fi
                done < $VEILERDBPATH/sync/${PKGNAME[$i]}/additionaldownloads
            fi
       popd &> /dev/null
    }
}
getPatches(){
    log_info imp "Getting patch(es) [ ${YELLOW}${#PKGNAME[@]}${WHITE} ]..."
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
            if [ -s "$VEILERDBPATH/sync/${PKGNAME[$i]}/patches" ]; then
                if [ $VEILERQUIET -eq 0 ]; then
                    wget -nv -nc --input-file "$VEILERDBPATH/sync/${PKGNAME[$i]}/patches"
                else
                    wget -nv -q --show-progress --input-file "$VEILERDBPATH/sync/${PKGNAME[$i]}/patches"
                fi
            fi
        popd &> /dev/null
    }
}
verifyChecksums(){
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        if [ $VEILERSKIPINTEGRITY -eq 0 ]; then
            echo -ne "\r${YELLOW}Important >>> ${GRAY}("$((i+1))"/"${#PKGNAME[@]}") ${WHITE}Verifying package integrity ${DARKBLUE}|||${WHITE} ${PKGNAME[$i]}                                     ${NC}"
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            unset MOONPKGNAME MOONPKGVERSION MOONPKG SRC REQDSKSPC INSTALLEDSIZE WODOCINSTALLEDSIZE DOWNLOADSIZE 
            if [ -n "$MOONBASEPKG" ]; then
                source $VEILERDBPATH/sync/$MOONBASEPKG/info
                unset MOONPKG SRC REQDSKSPC INSTALLEDSIZE WODOCINSTALLEDSIZE DOWNLOADSIZE 
                pushd "build-"$MOONPKGNAME"-"$MOONPKGVERSION"" &> /dev/null
                    sha256sum -c --quiet integrity.sha256 || log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to verify package integrity for base package ${RED}>>>${WHITE} $MOONPKGNAME"
                popd &> /dev/null
                if [ $VEILERSKIPCLEAN -eq 0 ]; then
                    tar -cf "build-$MOONPKGNAME-$MOONPKGVERSION.tar.gz" "build-$MOONPKGNAME-$MOONPKGVERSION"  || log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE}Failed to archive the base package ${RED}>>>${WHITE}$MOONPKGNAME" 
                fi
            fi  
            pushd "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" &> /dev/null
                sha256sum -c --quiet integrity.sha256 || log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to verify package integrity for package ${RED}>>>${WHITE} ${PKGNAME[$i]}"
            popd &> /dev/null
            sleep 0.1
        fi
        if [ $VEILERSKIPCLEAN -eq 0 ]; then
            tar -cf "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}".tar.gz" "build-"${PKGNAME[$i]}"-"${PKGVERSION[$i]}"" || log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE}Failed to archive the package" 
        fi
    }; echo
}
buildPackages(){
    export MAKEFLAGS="$MAKEFLAGS"
    export PKG_CONFIG_PATH="$PKGCONFPATH"
    USEFLAGS=( ${USEFLAGS[@]} )
    log_info imp "Building the package(s)..."
    GLOBALUSEFLAGS=( ${USEFLAGS[@]} )
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        echo -e "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Building ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
        pushd "build-${PKGNAME[$i]}-${PKGVERSION[$i]}" &> /dev/null
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            unset MOONPKGNAME MOONPKGVERSION DESC SRC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
            if [ $VEILERERREXIT -eq 0 -a $TRAPSET -eq 0 ]; then trap 'log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to build the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"' ERR; fi
            if [ -s /etc/Veiler/package.use ]; then
                while read pkg; do
                    if [ $(echo $pkg | sed 's/->.*//; s/^s//g') == "${PKGNAME[$i]}" ]; then
                        USEFLAGS=( "$(echo $pkg | sed "s/.*->//; s/^\s*//")" )
                        USEFLAGS=( $USEFLAGS )
                    fi
                done < /etc/Veiler/package.use
            fi
            if [ -n "$MOONBASEPKG" ]; then
                if [ ! -d $MOONPKG ]; then mkdir $MOONPKG; fi
                source $VEILERDBPATH/sync/$MOONBASEPKG/info
                cd ..
                tar xf "build-$MOONPKGNAME-$MOONPKGVERSION.tar.gz"
                cd "build-$MOONPKGNAME-$MOONPKGVERSION"
            fi
            if [ $VEILERSKIPCLEAN -eq 0 ]; then
                if [ -d "$MOONPKG" ]; then rm -rf "$MOONPKG"; fi
                if [ $VEILERQUIET -eq 1 ]; then
                    if [ $VEILERNOROOT -eq 0 ]; then
                         su -c "mkdir -p $MOONPKG && tar -xf "$MOONPKG".* -C $MOONPKG --strip-components=1" veiler-build-user
                    else
                        mkdir -p $MOONPKG && tar -xf "$MOONPKG".* -C $MOONPKG --strip-components=1
                    fi
                else
                    if [ $VEILERNOROOT -eq 0 ]; then
                        su -c "mkdir -p $MOONPKG && tar -xvf "$MOONPKG".* -C $MOONPKG --strip-components=1" veiler-build-user
                    else
                        mkdir -p $MOONPKG && tar -xvf "$MOONPKG".* -C $MOONPKG --strip-components=1
                    fi
                fi
            fi
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            unset DESC SRC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
            if [ -n "$MOONBASEPKG" ]; then
                cd ..
                cd "build-$MOONPKGNAME-$MOONPKGVERSION"
            fi
            pushd "$MOONPKG" &> /dev/null 
                if [ $VEILERNOROOT -eq 0 ]; then
                    if [ $VEILERQUIET -eq 1 ]; then
                        su -c "VEILERDEST=$VEILERDEST VEILERPREFIX=$VEILERPREFIX VEILERDBPATH=$VEILERDBPATH VEILERQUIET=$VEILERQUIET VEILERDOC=$VEILERDOC VEILERTESTS=$VEILERTESTS USEFLAGS=\"${USEFLAGS[*]}\" ../MOONBUILD build" veiler-build-user > /dev/null
                    else
                        su -c "VEILERDEST=$VEILERDEST VEILERPREFIX=$VEILERPREFIX VEILERDBPATH=$VEILERDBPATH VEILERQUIET=$VEILERQUIET VEILERDOC=$VEILERDOC VEILERTESTS=$VEILERTESTS USEFLAGS=\"${USEFLAGS[*]}\" ../MOONBUILD build" veiler-build-user
                    fi
                else
                    if [ $VEILERQUIET -eq 1 ]; then
                       VEILERDEST=$VEILERDEST VEILERPREFIX=$VEILERPREFIX USEFLAGS="$BUFFER" VEILERDBPATH=$VEILERDBPATH VEILERDOC=$VEILERDOC VEILERQUIET=$VEILERQUIET VEILERTESTS=$VEILERTESTS USEFLAGS="${USEFLAGS[*]}" ../MOONBUILD build > /dev/null
                    else
                        VEILERDEST=$VEILERDEST VEILERPREFIX=$VEILERPREFIX USEFLAGS="$BUFFER" VEILERDBPATH=$VEILERDBPATH VEILERDOC=$VEILERDOC VEILERQUIET=$VEILERQUIET VEILERTESTS=$VEILERTESTS USEFLAGS="${USEFLAGS[*]}" ../MOONBUILD build
                    fi
                fi
            popd &> /dev/null
            if [ $VEILERERREXIT -eq 0 -a $TRAPSET -eq 1 ]; then trap 'log_err "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Failed to install the package ${RED}>>> ${WHITE}${PKGNAME[$i]}"' ERR; TRAPSET=2; fi
            if [ $VEILERONLYBUILD -eq 0 ]; then 
                echo -e "${GRAY}($((i+1))/${#PKGNAME[@]})${WHITE} Installing ${YELLOW}>>> ${WHITE}${PKGNAME[$i]}${NC}"
                pushd "$MOONPKG" &> /dev/null
                    if [ $VEILERNOROOT -eq 0 ]; then
                        if [ $VEILERQUIET -eq 1 ]; then
                            VEILERPREFIX=$VEILERPREFIX VEILERDBPATH=$VEILERDBPATH VEILERQUIET=$VEILERQUIET ../MOONBUILD install > /dev/null
                        else
                            VEILERPREFIX=$VEILERPREFIX VEILERDBPATH=$VEILERDBPATH VEILERQUIET=$VEILERQUIET ../MOONBUILD install
                        fi
                    fi
                popd &> /dev/null
                if [ -f "$VEILERDBPATH/local/${PKGNAME[$i]}/files" ]; then
                    while read currentfile; do
                        rm -f "$VEILERDEST/$currentfile"
                    done < "$VEILERDBPATH/local/${PKGNAME[$i]}/files"
                fi
                cp -r "$VEILERDBPATH/sync/${PKGNAME[$i]}" "$VEILERDBPATH/local/"
                source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
                unset MOONBASEPKG MOONPKGNAME MOONPKGVERSION DESC SRC INSTALLEDSIZE WODOCINSTALLEDSIZE REQDSKSPACE DOWNLOADSIZE 
                cd "$MOONPKG"/DEST
                if [ -s $VEILERDBPATH/sync/${PKGNAME[$i]}/docfiles ]; then
                    if [ $VEILERDOC -eq 0 ]; then
                        while read file; do
                            if [ $VEILERQUIET -eq 1 ]; then
                                rm -f "./$VEILERPREFIX$file"
                            else
                                rm -fv "./$VEILERPREFIX$file"
                            fi
                        done < $VEILERDBPATH/sync/${PKGNAME[$i]}/docfiles
                    fi
                fi
                find . ! -type d | sed 's/^.//' > $VEILERDBPATH/local/${PKGNAME[$i]}/files 
                if [ ! -d $VEILERDEST ]; then mkdir -p $VEILERDEST; fi
                if [ $VEILERQUIET -eq 1 ]; then
                    cp -fra ./* $VEILERDEST
                else
                    cp -frva ./* $VEILERDEST
                fi
            fi
        popd &> /dev/null
        echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Completed the build${DARKBLUE} >>> ${WHITE}${PKGNAME[$i]}${NC}"
    }
    unset MAKEFLAGS
    trap - ERR
}
uninstallPackages(){
    log_info imp "Uninstalling the package(s)"
    local UNINSTALLED=0
    for((i=0; i < ${#PKGNAME[@]}; i++)){
        echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Uninstalling ${BLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
        if [ $VEILERERREXIT -eq 0 ]; then trap 'log_err "${GRAY}($((i+1)/${#PKGNAME[@]}))${WHITE} Failed to uninstall the package ${RED}>>>${WHITE} ${PKGNAME[$i]}"' ERR; fi
        if [ -f $VEILERDBPATH/local/${PKGNAME[$i]}/files ]; then
            while read file; do
                if [ $VEILERQUIET -eq 1 ]; then
                    rm -f "$file"
                else
                    rm -fv "$file"
                fi
            done < $VEILERDBPATH/local/${PKGNAME[$i]}/files
            UNINSTALLED=1
        fi
        rm -rf "$VEILERDBPATH/local/${PKGNAME[$i]}"
        echo -e "${GRAY}($((i+1))/${#PKGNAME[@]}) ${WHITE}Successfully uninstalled ${DARKBLUE}>>> ${WHITE}${PKGNAME[$i]}${NC}"
        if [ $UNINSTALLED -eq 1 ]; then
            log_info notice "Nothing was uninstalled."
        fi
    }
    trap - ERR
}
push(){
    STACK+=( "$1" )
}
pop(){
    unset 'STACK[$((${#STACK[@]} - 1))]'
}
resolvedeps(){
    # --- Start dependency calculating ---
    if [ $VEILERSKIPDEPS -eq 0 ]; then
        second_animation "$(log_info imp "Calculating dependencies")"
        PACKAGES=( "$@" )
        USEFLAGS=( $USEFLAGS )
        GLOBALUSEFLAGS=( ${USEFLAGS[@]} )
        for PACKAGE in ${PACKAGES[@]}; do
            if [ ${#GLOBALUSEFLAGS[@]} -gt 0 -o -s /etc/Veiler/package.use ]; then
                USEFLAGS=( ${GLOBALUSEFLAGS[@]} )
                while read pkg; do
                    if [ $(echo $pkg | sed 's/->.*//; s/\s//g') == "$PACKAGE" ]; then
                        BUFFER=( "$(echo $pkg | sed "s/.*->//; s/^\s*//")" )
                        USEFLAGS=( $BUFFER )
                    fi
                done < /etc/Veiler/package.use
                for FLAG in ${USEFLAGS[@]}; do
                     if [ -s "$VEILERDBPATH/sync/$PACKAGE/optdependencies" ]; then
                         while read pkg_line; do
                             if [ "$FLAG" == "$(echo $pkg_line | sed 's/ .*//')" ]; then
                                 PACKAGES+=( $(echo $pkg_line | sed 's/.* //' ) )
                             fi
                         done < "$VEILERDBPATH/sync/$PACKAGE/optdependencies"
                     fi
                 done
            fi
        done
        if [ $VEILERTESTS -eq 1 ]; then
            for PACKAGE in ${PACKAGES[@]}; do
                if [ -s ""$VEILERDBPATH"/sync/"$PACKAGE"/testdependencies" ]; then
                    while read dependency; do
                        PACKAGES+=( "$dependency" )
                    done < ""$VEILERDBPATH"/sync/"$PACKAGE"/testdependencies"
                fi
            done
        fi
        for PACKAGE in ${PACKAGES[@]}; do
            push $PACKAGE
            while [ ${#STACK[@]} -gt 0 ]; do
                CURRENTPACKAGE=${STACK[$((${#STACK[@]} - 1))]}
                DEPS=()
                if [ -f "$VEILERDBPATH/sync/$CURRENTPACKAGE/dependencies" ]; then
                    while read dependency; do
                        DEPS+=( "$dependency" )
                    done < "$VEILERDBPATH/sync/$CURRENTPACKAGE/dependencies"
                fi
                if [ ${visited[$CURRENTPACKAGE]} ]; then pop && continue; fi
                for DEPENDENCY in ${DEPS[@]}; do
                    push $DEPENDENCY
                    if [ ${visited[$DEPENDENCY]} ]; then pop && continue; fi
                    if [ ! -d "$VEILERDBPATH/local/$DEPENDENCY" ]; then
                        break
                    fi
                    visited[$DEPENDENCY]="yes"
                    pop
                done
                if [[ ! -d "$VEILERDBPATH/local/$CURRENTPACKAGE" && $(checkifallvisited "$CURRENTPACKAGE") == "yes" && "${visited[$CURRENTPACKAGE]}" != "yes" ]]; then
                    RESOLVEDPACKAGES+=("$CURRENTPACKAGE")
                    visited[$CURRENTPACKAGE]="yes"
                fi
                if [[ $(checkifallvisited "$CURRENTPACKAGE") == "yes" && "${visited[$CURRENTPACKAGE]}" != "yes" ]]; then
                   RESOLVEDPACKAGES+=("$CURRENTPACKAGE")
                fi
                if [ "$(checkifallvisited "$CURRENTPACKAGE")" == "yes" ]; then
                    visited[$CURRENTPACKAGE]="yes"
                fi
            done
        done
        veiler_stop_animation
        PACKAGES=( ${RESOLVEDPACKAGES[@]} )
        makepkgarray "${PACKAGES[@]}"
    else
        makepkgarray "$@"
        return
    fi
    # --- End dependency calculating ---
}
makepkgarray(){
    PKGVERSION=()
    PKGNAME=()
    while [ $# -gt 0 ]; do
        if [ -f $VEILERDBPATH/sync/$1/info ]; then
            local BUFFERPKGVERSION="$(sed -n 's/^MOONPKGVERSION=//; s/"$//; s/^"//p' $VEILERDBPATH/sync/$1/info)"
            local BUFFERPKGNAME="$(sed -n 's/^MOONPKGNAME=//; s/"$//; s/^"//p' $VEILERDBPATH/sync/$1/info)"
        fi
        if [ -z "$BUFFERPKGVERSION" -a -z "$BUFFERPKGNAME" ]; then
            log_warn "No valid information related to ${YELLOW}$1${WHITE} could be found. Skipping this package..."
            shift
            continue
        elif [ -z "$BUFFERPKGVERSION" ]; then
            log_warn "No valid version could be found for ${YELLOW}$1${WHITE}. Skipping this package..." 
            shift
            continue
        elif [ -z "$BUFFERPKGNAME" ]; then
            log_warn "No valid name could be found for ${YELLOW}$1${WHITE}. Skipping this package..."
            shift
            continue
        fi
        PKGVERSION+=( "$BUFFERPKGVERSION" )
        PKGNAME+=( "$BUFFERPKGNAME" )
        BUFFERPKGVERSION=
        BUFFERPKGNAME=
        shift
    done
}
checkifallvisited(){
    if [ -f "$VEILERDBPATH/sync/$CURRENTPACKAGE/dependencies" ]; then
        while read dependency; do
            if [ ! ${visited[$dependency]} ]; then return; fi
        done < "$VEILERDBPATH/sync/$CURRENTPACKAGE/dependencies"
    fi
    echo "yes"
}
# --- End Functions ---
for((i=0; i < ${#OPTIONS[@]}; i++)){
    case ${OPTIONS[$i]} in
        --quiet)
            if [ $VEILERQUIET -eq 0 ]; then VEILERQUIET=1; else log_err "Quiet mode already enabled!"; fi
        ;;
        --documentation)
            if [ $VEILERDOC -eq 0 ]; then VEILERDOC=1; else log_err "Documentation already enabled!"; fi
        ;;
        --tests)
            if [ $VEILERTESTS -eq 0 ]; then VEILERTESTS=1; else log_err "Tests already enabled!"; fi
        ;;
        --ask)
            if [ $VEILERASK -eq 0 ]; then VEILERASK=1; else log_err "Confirmation prompts already enabled!"; fi
        ;;
        --skip-description)
            if [ $VEILERSKIPDESC -eq 0 ]; then VEILERSKIPDESC=1; else log_err "Description skipping already enabled!"; fi
        ;;
        --build-only)
            if [ $VEILERONLYBUILD -eq 0 ]; then VEILERONLYBUILD=1; else log_err "Build only mode already enabled!"; fi
        ;;
        --no-root)
            if [ $VEILERNOROOT -eq 0 ]; then VEILERNOROOT=1; else log_err "No root alreay enabled!"; fi
        ;;
        --with-dest)
            VEILERDEST=${OPTIONS[$((i+1))]}; ((i++))
        ;;            
        --skip-deps)
            if [ $VEILERSKIPDEPS -eq 0 ]; then VEILERSKIPDEPS=1; else log_err "Skipping dependencies already enabled!"; fi
        ;;
        --skip-clean)
            if [ $VEILERSKIPCLEAN -eq 0 ]; then VEILERSKIPCLEAN=1; else log_err "Skipping cleaning already enabled!"; fi
        ;;
        --skip-installed)
            if [ $VEILERSKIPINST -eq 0 ]; then VEILERSKIPINST=1; else log_err "Skipping installed packages already enabled!"; fi
        ;;
        --megabytes)
            if [ $VEILERMBE -eq 0 ]; then VEILERMBE=1; else log_err "Showing size in megabytes already enabled!"; fi
        ;;
        --skip-integrity)
            if [ $VEILERSKIPINTEGRITY -eq 0 ]; then VEILERSKIPINTEGRITY=1; else log_err "Skipping verifying package integrity is already enabled!"; fi
        ;;
        --no-errexit)
            if [ $VEILERERREXIT -eq 0 ]; then VEILERERREXIT=1; else log_err "Not exiting upon errors already enabled!"; fi
        ;;
        --config)
            ((i++))
        ;;
        *)
            log_err "Invalid option ${GRAY}${OPTIONS[$i]}${NC}"
        ;;
    esac    
}
# -- End option parsing --
if [ $VEILERSKIPINST -eq 1 ]; then
    set -- $(checkIfAlreadyInstalled ${ARGUMENTS[@]})
else
    set -- ${ARGUMENTS[@]}
fi
case $1 in
	unveil)
        shift
        if [ -z "$1" ]; then
            log_err "Nothing to install."
        fi
        checkifroot
        BUFFER=$(echo $VEILERDEST | cut -c1 )
        if [ $BUFFER != "/" ]; then
            log_err "Please provide an absolute path for ${GRAY}--with-dest"
        fi
        if [ $VEILERONLYBUILD -eq 0 ]; then
            log_info notice "Packages will be installed in $VEILERDEST"
        fi
        play_animation "$(log_info activity "Checking if packages exist")"
        sleep 0.1
        for PACKAGE in "$@"; do
            if [ ! -d "$VEILERDBPATH/sync/$PACKAGE" ]; then veiler_stop_animation ; log_err "The requested package ${YELLOW}$PACKAGE${WHITE} could not be found on the database"; fi
        done
        veiler_stop_animation
        resolvedeps "$@"
        echo -ne "\n${YELLOW}Packages to be installed ${GRAY}(${#PKGNAME[@]}): ${NC}"
        for((i=0; i < ${#PKGNAME[@]}; i++)){
            if [ -f $VEILERDBPATH/local/"${PKGNAME[$i]}"/info -a -n "${PKGNAME[$i]}" ]; then
                LOCALPKGVERSION="$(sed -n 's/^MOONPKGVERSION=//; s/"$//; s/^"//p' $VEILERDBPATH/local/"${PKGNAME[$i]}"/info)"
                if [ "${PKGVERSION[$i]}" != "$LOCALPKGVERSION" ]; then
                    echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${WHITE} -> "${PKGNAME[$i]}" ${GRAY}("${PKGVERSION[$i]}")${NC}   "
                else
                    echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("$LOCALPKGVERSION")${NC}  "
                fi
            elif [ -n "${PKGNAME[$i]}" ]; then 
                echo -ne "${WHITE}"${PKGNAME[$i]}" ${GRAY}("${PKGVERSION[$i]}")${NC}  "
            fi
        }
        echo; echo
        for PACKAGE in ${PKGNAME[@]}; do
            SPACEBUFFER=$(sed -n 's/^REQDSKSPC=//p' $VEILERDBPATH/sync/$PACKAGE/info)
            SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
	        ((TOTALDSR+=SPACEBUFFER))
	        SPACEBUFFER=$(sed -n 's/^DOWNLOADSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
	        SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
	        ((TOTALDOWNLOADSIZE+=SPACEBUFFER))
            SPACEBUFFER=$(sed -n 's/^INSTALLEDSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
	        SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
	        ((TOTALINSTSIZE+=SPACEBUFFER))
	        SPACEBUFFER=$(sed -n 's/^WODOCINSTALLEDSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
            SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
	    ((WODOCINSTSIZE+=SPACEBUFFER))
	    done
        AVAILSPACE=$(df --output=avail | sed -n '2p')
        AVAILSPACE=$((AVAILSPACE*1024))
        if [ $VEILERDOC -eq 1 ]; then
            if [ $AVAILSPACE -le $((TOTALINSTSIZE+TOTALDSR)) ]; then
                log_err noexit "${RED}ERROR >>>${WHITE} Insufficient disk space!"
                log_err noexit "${RED}ERROR >>>${WHITE} Required ${YELLOW}> $(((TOTALINSTSIZE+TOTALDSR)/1024/1024)) MiB <${NC} "
                log_err noexit "${RED}ERROR >>>${WHITE} Available ${YELLOW}> $((AVAILSPACE/1024/1024)) MiB <${NC}"
                exit 1
            fi
        else
            if [ $AVAILSPACE -le $((WODOCTOTALINSTSIZE+TOTALDSR)) ]; then
                log_err noexit "${RED}ERROR >>>${WHITE} Insufficient disk space!"
                log_err noexit "${RED}ERROR >>>${WHITE} Required ${YELLOW}> $(((WODOCTOTALINSTSIZE+TOTALDSR)/1024/1024)) MiB <${NC} "
                log_err noexit "${RED}ERROR >>>${WHITE} Available ${YELLOW}> $((AVAILSPACE/1024/1024)) MiB <${NC}"
                exit 1
            fi
        fi
        if [ $VEILERMBE -eq 1 ]; then
	        ((TOTALDSR=TOTALDSR/1024/1024))
	        echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR" MiB${NC}"
	        ((TOTALDOWNLOADSIZE=TOTALDOWNLOADSIZE/1024/1024))
            echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE" MiB${NC}"
	        ((TOTALINSTSIZE=TOTALINSTSIZE/1024/1024))
	        echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE" MiB${NC}"
	        ((WODOCINSTSIZE=WODOCINSTSIZE/1024/1024))
            echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE" MiB${NC}"
	    else
	        ((TOTALDSR/=1024))
            echo -e "${DARKBLUE}*** ${BLUE}Total disk space required: ${WHITE}"$TOTALDSR" KiB${NC}"
            ((TOTALDOWNLOADSIZE/=1024))
	        echo -e "${DARKBLUE}*** ${BLUE}Total download size: ${WHITE}"$TOTALDOWNLOADSIZE" KiB${NC}"
	        ((TOTALINSTSIZE/=1024))
            echo -e "${DARKBLUE}*** ${BLUE}Total installed size: ${WHITE}"$TOTALINSTSIZE" KiB${NC}"
            ((WODOCINSTSIZE/=1024))
	        echo -e "${DARKBLUE}*** ${BLUE}Total installed size ( without documentation ): ${WHITE}"$WODOCINSTSIZE" KiB${NC}"
	    fi
        if [ "$VEILERASK" -eq 1 ]; then
            echo -ne "\n${YELLOW}||| ${WHITE}Proceed with the installation?[y/n]: "
            read -n 1
            if [ "$REPLY" == "y" -o "$REPLY" == "yes" -o "$REPLY" == "Y" ]; then
                true; echo -e "${NC}"
            else
                echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
            fi
        fi
        clean
        log_info notice "Changing directory to $VEILERCACHEPATH..."
        pushd $VEILERCACHEPATH &> /dev/null 
            getBuildTarballs 
            extractBuildTarballs 
            getSources 
            getPatches
            verifyChecksums 
            buildPackages
            if [ $VEILERONLYBUILD -eq 1 ]; then
                log_info notice "The package manager has finished building the packages, but has not installed them. Goodluck with whatever you are doing!"
                log_info imp "The build directories can be found at $VEILERCACHEPATH"
            fi
        popd &> /dev/null
    ;;
	veil)
        shift
        if [ -z "$1" ]; then
            log_err "No package was provided!"
        fi
        checkifroot
        play_animation "$(log_info activity "Checking if packages exist")"
        sleep 0.1
        for PACKAGE in "$@"; do
            if [ ! -d "$VEILERDBPATH/sync/$PACKAGE" ]; then veiler_stop_animation; log_err "The requested package ${YELLOW}$PACKAGE${WHITE} could not be found on the database.${NC}"; fi
        done
        sleep 0.1
        veiler_stop_animation
        makepkgarray $@
        for PACKAGE in ${PKGNAME[@]}; do
            SPACEBUFFER=$(sed -n 's/^INSTALLEDSIZE=//p' $VEILERDBPATH/sync/$PACKAGE/info)
            SPACEBUFFER="$(echo $SPACEBUFFER | sed 's/"//g')"
            ((TOTALUNINSTSIZE+=SPACEBUFFER))
        done
        if [ $VEILERMBE -eq 1 ]; then
            ((TOTALUNINSTSIZE=TOTALUNINSTSIZE/1024/1024))
            echo -e "\n${DARKBLUE}***${BLUE} Total uninstalled size: ${WHITE}$TOTALUNINSTSIZE${NC} MiB"
        else
            ((TOTALUNINSTSIZE=TOTALUNINSTSIZE/1024))
            echo -e "\n${DARKBLUE}***${BLUE} Total uninstalled size: ${WHITE}$TOTALUNINSTSIZE${NC} KiB"
        fi
        echo -ne "\n${YELLOW}Packages to be uninstalled ${GRAY}(${#PKGNAME[@]}): ${NC}"
        for((i=0; i < ${#PKGNAME[@]}; i++)){
            echo -ne "${WHITE}${PKGNAME[$i]} ${GRAY}(${PKGVERSION[$i]})${NC}   "
        }
        if [ $VEILERASK -eq 1 ]; then
            echo -ne "\n\n${BLUE}||| ${WHITE}Proceed with the uninstallation?[y/n]: ${NC}"
            read -n 1
            if [ $REPLY == "y" -o $REPLY == "yes" -o $REPLY == "Y" ]; then
                true; echo -e "${NC}"
            else
                echo -e "\n${WHITE}Goodbye!${NC}"; exit 0
            fi
        else 
            echo
        fi
        log_info notice "Changing directory to $VEILERCACHEPATH..."
        uninstallPackages
	;;
	strengthen)
        checkifroot
        log_info notice "It is advised to run ${BLUE}$0 ${YELLOW}sync${WHITE} before performing this operation."
        shift
        PACKAGES=( $(find $VEILERDBPATH/local -type d | sed '1d' | sed "s@$VEILERDBPATH/local\/@@") )
        for PACKAGE in ${PACKAGES[@]}; do
            if [ -f "$VEILERDBPATH/local/$PACKAGE/info" -a -f "$VEILERDBPATH/sync/$PACKAGE/info" ]; then 
                source "$VEILERDBPATH/local/$PACKAGE/info"
                LOCALPKGVERSION=$MOONPKGVERSION
                source "$VEILERDBPATH/sync/$PACKAGE/info"
                SYNCPKGVERSION=$MOONPKGVERSION
                if [ $LOCALPKGVERSION != $SYNCPKGVERSION ]; then
                    UPGRADEDPACKAGES+=( "$PACKAGE" )
                    UPGRADEDPACKAGESLOCALVERSION+=( "$LOCALPKGVERSION" )
                    UPGRADEDPACKAGESSYNCVERSION+=( "$SYNCPKGVERSION" )
                fi
            else
                log_warn "No valid information file could be found for the package ${BLUE}$PACKAGE${NC}"
            fi
        done
        if [ ${#UPGRADEDPACKAGES[@]} -eq 0 ]; then
            log_err "Nothing to upgrade. Exiting"
        fi
        BUFFER=$(echo $VEILERDEST | cut -c1 )
        if [ $BUFFER != "/" ]; then
            log_err "Please provide an absolute path for ${GRAY}--with-dest"
        fi
        if [ $VEILERONLYBUILD -eq 0 ]; then
            log_info notice "Packages will be upgraded in $VEILERDEST"
        fi
        resolvedeps ${UPGRADEDPACKAGES[@]}
        echo -en "${WHITE}\nPackages to be upgraded ${GRAY}(${#UPGRADEDPACKAGES[@]}): "
        for((i=0; i < ${#UPGRADEDPACKAGES[@]}; i++)){
            echo -ne "${WHITE}${UPGRADEDPACKAGES[$i]} ${GRAY}(${UPGRADEDPACKAGESLOCALVERSION[$i]})${YELLOW} -> ${WHITE}${UPGRADEDPACKAGES[$i]} ${GRAY}(${UPGRADEDPACKAGESSYNCVERSION[$i]})${NC}   "
        }; echo
        echo -en "${WHITE}\nNew additional dependencies to be installed: ${NC}"
        if [ ${#ADDITIONALDEPS[@]} -ne 0 ]; then
            for PACKAGE in ${ADDITIONALDEPS[@]}; do
                if [ -f $VEILERDBPATH/sync/$PACKAGE/info ]; then
                    source $VEILERDBPATH/sync/$PACKAGE/info
                    printf "${WHITE}${MOONPKGNAME} ${GRAY}(${MOONPKGVERSION})   "
                fi
            done; echo -e "${NC}\n"
        else
            echo -e "${BLUE}(none)${NC}\n"
        fi
        for((i=0; i < ${#PKGNAME[@]}; i++)){
            SIZEBUFFER=0
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            SIZEBUFFER=$((SIZEBUFFER + INSTALLEDSIZE))
            if [ -f $VEILERDBPATH/local/${PKGNAME[$i]}/info ]; then source $VEILERDBPATH/local/${PKGNAME[$i]}/info; fi
            SIZEBUFFER=$((SIZEBUFFER - INSTALLEDSIZE))
            TOTALUPGRADESIZE=$(( $TOTALUPGRADESIZE + $SIZEBUFFER ))
            SIZEBUFFER=0
            source $VEILERDBPATH/sync/${PKGNAME[$i]}/info
            SIZEBUFFER=$((SIZEBUFFER + INSTALLEDSIZEWODOC))
            if [ -f $VEILERDBPATH/local/${PKGNAME[$i]}/info ]; then source $VEILERDBPATH/local/${PKGNAME[$i]}/info; fi
            SIZEBUFFER=$((SIZEBUFFER - INSTALLEDSIZEWODOC))
            TOTALUPGRADESIZEWODOC=$(( $TOTALUPGRADESIZEWODOC + $SIZEBUFFER))
            SIZEBUFFER=0
        }
        AVAILSPACE=$(df --output=avail | sed -n '2p')
        if [ $AVAILSPACE -le $((TOTALUPGRADESIZE+TOTALDSR)) ]; then
            log_err noexit "${RED}ERROR >>>${WHITE} Insufficient disk space!" 
            log_err noexit "${RED}ERROR >>>${WHITE} Required ${YELLOW}> $((TOTALUPGRADESIZE/1024/1024)) MiB <${NC} "
            log_err noexit "${RED}ERROR >>>${WHITE} Available ${YELLOW}> $((AVAILSPACE/1024/1024)) MiB <${NC}"
            exit 1
        fi
        if [ $AVAILSPACE -le $((TOTALUPGRADESIZEWODOC+TOTALDSR)) ]; then
            log_err noexit "${RED}ERROR >>>${WHITE} Insufficient disk space!"
            log_err noexit "${RED}ERROR >>>${WHITE} Required ${YELLOW}> $((TOTALUPGRADESIZEWODOC/1024/1024)) MiB <${NC} "
            log_err noexit "${RED}ERROR >>>${WHITE} Available ${YELLOW}> $((AVAILSPACE/1024/1024)) MiB <${NC}"
            exit 1
        fi
        echo -e "${DARKBLUE}***${BLUE} Total upgrade size:${WHITE} $TOTALUPGRADESIZE${NC}"
        echo -e "${DARKBLUE}***${BLUE} Total upgrade size ( without documentation ):${WHITE} $TOTALUPGRADESIZEWODOC${NC}"
        if [ $VEILERASK -eq 1 ]; then
            echo -ne "\n${BLUE}||| ${WHITE}Proceed with the upgrade?[y/n]: ${NC}"
            read -n 1
            if [ $REPLY == "y" -o $REPLY == "Y" -o $REPLY == "yes" ]; then
                true; echo 
            else
               echo -e "\n${BLUE}Goodbye!${NC}"; exit 0
            fi
        fi
        clean
        log_info notice "Changing directory to $VEILERCACHEPATH..."
        pushd $VEILERCACHEPATH &> /dev/null 
            getBuildTarballs 
            extractBuildTarballs 
            getSources 
            verifyChecksums 
            buildPackages
            if [ $VEILERONLYBUILD -eq 1 ]; then
                log_info notice "The package manager has finished building the packages, but has not installed them. Goodluck with whatever you are doing!"
                log_info imp "The build directories can be found at $VEILERCACHEPATH"
            fi
        popd &> /dev/null
	;;
    info)
        PACKAGES=()
        shift
        if [ -z $1 ]; then
            log_err "No package provided!"
        fi
        for((i=1; i <= $#; i++)){
            if [ ! -d "$VEILERDBPATH/local/${!i}" ]; then
                log_warn "${!i} is not installed."
            else
                PACKAGES+=( ${!i} )
            fi
        }
        for((i=0; i < ${#PACKAGES[@]}; i++)){
            if [ -f "$VEILERDBPATH/local/${PACKAGES[$i]}/info" ]; then
                source "$VEILERDBPATH/local/${PACKAGES[$i]}/info" 
                echo -e "${YELLOW}$MOONPKGNAME${NC} ${GRAY}($MOONPKGVERSION)${NC}"
                echo -e "\t${WHITE}$DESC${NC}"
            else
                log_warn "Could not find a valid information file for ${YELLOW}${PACKAGES[$i]}"
            fi
        }
    ;;
	help)
        echo -e "${YELLOW}$0 Usage:${WHITE} $0 <COMMAND> <OPTIONS> ${NC}"
		echo -e "${WHITE}$0 unveil|veil <OPTIONS> [PACKAGE]${NC}"
		echo -e "${WHITE}$0 Options:${NC}" 
        echo -e "${GRAY}--quiet${NC}${WHITE}         : Displays quiet output, not too detailed.${NC}"
	    echo -e "${GRAY}--documentation${NC}${WHITE} : Enables documentation (this might install extra dependencies)${NC}"
        echo -e "${GRAY}--test${NC}${WHITE}          : Enables test harnesses${NC}" 
        echo -e "${GRAY}--ask${NC}${WHITE}           : Use confirmation prompts${NC}"
        echo -e "${GRAY}--no-root${NC}${WHITE}       : Don't use superuser priveledges ( might cause errors when installing in priveleged directories )${NC}"
        echo -e "${GRAY}--skip-clean${NC}${WHITE}    : Skip deleting existing build directories in cache ( will cause the package manager to not start building from scratch${NC}"
        echo -e "${GRAY}--skip-deps${NC}${WHITE}     : Skip dependency check ( can break packages )${NC}"
        echo -e "${GRAY}--skip-installed${NC}${WHITE}: Skip installing packages provided to the package manager if they are already installed on the system.${NC}"
        echo -e "${GRAY}--megabytes${NC}${WHITE}     : Show size in megabytes instead of kilobytes${NC}"
        echo -e "${GRAY}--skip-integrity${NC}${WHITE}: Do not verify package integrity ( unsafe and can lead to security issues and building corrupted packages )${NC}"
        echo -e "${GRAY}--no-errexit${NC}${WHITE}    : Do not exit upon an error WHILE building the packages ( might cause you to have broken packages installed lol )${NC}"
        echo -e "${GRAY}--config <PATH>${NC}${WHITE} : Use a custom configuration file instead of the default one." 
		echo -e "${WHITE}unveil     : Installs a package from source.${NC}"
        echo -e "${WHITE}   -> ${GRAY}--with-dest <DESTDIR> ${WHITE}: Installs package into <DESTDIR> instead of default /${NC}"
        echo -e "${WHITE}   -> ${GRAY}--build-only          ${WHITE}: This option makes the package manager only compile and build the package and skip installing it.${NC}"
		echo -e "${WHITE}veil       : Uninstalls a package installed on the system${NC}"
		echo -e "${WHITE}strengthen : Updates all packages installed on the system${NC}"
		echo -e "${WHITE}search     : Matches regex with a package name in the package database${NC}"
        echo -e "${WHITE}   -> ${GRAY}--skip-description: ${WHITE}To avoid matching the regex with found descriptions${NC}"
		echo -e "${WHITE}help       : Displays this output${NC}"
        echo -e "${WHITE}version    : Display package manager version${NC}"
        echo -e "${WHITE}info       : Display information about installed packages${NC}"
        echo -e "${WHITE}rmpkg      : Removes ${ALL}ALL${WHITE} the tarballs of the specified package in the cache ( useful for reducing disk space usage and making the package manager download the package build tarball again, which may be done if the maintainer has applied some patches to the build script )${NC}"
        echo -e "${WHITE}clearcache : Remove ${RED}EVERYTHING${WHITE} in the cache directory of the package manager.${NC}"
        echo -e "${WHITE}pkgs       : ${WHITE}Get number of all packages${NC}"
        echo -e "${WHITE}list       : ${WHITE}List all packages installed${NC}"
        echo -e "${YELLOW}Note: ${WHITE}See https://ilovetrees242.github.io/DevHelp/Website/Veiler.html for detailed information${NC}"
	;;
    version)
            echo -e "${WHITE}I like the ${YELLOW}moon${WHITE}, so this package manager is based of it. This is my 3rd great project out of 5, so I really admire this"
            echo "__    __  _____   o  ___    _____   _____  "
            echo "\ \  / / |     | | | | |   |     |  | ___\ " 
            echo " \ \/ /  | ----| | | | |_  | ----|  | |    "
            echo "  \__/   |_____  |_| |___| |_____   |_|    "
            echo -e "${NC}"
            echo -e "${YELLOW}Veiler ${WHITE}version 2.0.0${NC}"
    ;;
    search)
        shift
        FOUNDPACKAGES=()
        FOUNDPACKAGESVERSION=()
        FOUNDPACKAGESDESC=()
        FOUNDPACKAGESINSTALLED=()
        if [ -z $1 ]; then
            log_err "No package was provided!"
        fi
        if [ $VEILERSKIPDESC -eq 1 ]; then
            COUNT=0
            for((i=1; i <= $#; i++)){
                PACKAGES=$(find $VEILERDBPATH/sync -type d -name "*${!i}*")
                for PACKAGE in $PACKAGES; do
                    if [ -f $PACKAGE/info ]; then
                        source $PACKAGE/info 
                        FOUNDPACKAGES[$COUNT]="$MOONPKGNAME"
                        FOUNDPACKAGESVERSION[$COUNT]="$MOONPKGVERSION"
                        FOUNDPACKAGESDESC[$COUNT]="$DESC"
                        if [ -n ${FOUNDPACKAGES[$COUNT]} ]; then
                            if [ -d "$VEILERDBPATH/local/${FOUNDPACKAGES[$COUNT]}" ]; then
                                FOUNDPACKAGESINSTALLED[$COUNT]=" ${WHITE}||| ${YELLOW}Installed : ${WHITE}Yes${NC}"
                            else
                                FOUNDPACKAGESINSTALLED[$COUNT]=" ${WHITE}||| ${YELLOW}Installed : ${WHITE}No${NC}"
                            fi  
                            ((COUNT++))
                        fi
                    fi
                done
            }   
            for((i=0; i < ${#FOUNDPACKAGES[@]}; i++)){
                echo -ne "${BLUE}${FOUNDPACKAGES[$i]}${NC}"
                echo -ne "${GRAY}(${FOUNDPACKAGESVERSION[$i]})${NC}"
                echo -e "${FOUNDPACKAGESINSTALLED[$i]}"
                echo -e "\t${WHITE}${FOUNDPACKAGESDESC[$i]}${NC}"
            } | more
        else
            COUNT=0
            for((i=1; i <= $#; i++)){
                PACKAGES=$(ls $VEILERDBPATH/sync/)
                for PACKAGE in $PACKAGES; do
                    if [ -f $VEILERDBPATH/sync/$PACKAGE/info ]; then 
                        source $VEILERDBPATH/sync/$PACKAGE/info 
                        FOUNDPACKAGES[$COUNT]=$(echo $MOONPKGNAME | grep "${!i}")
                        FOUNDPACKAGESDESC[$COUNT]=$(echo $DESC | grep "${!i}")
                        if [[ -n "${FOUNDPACKAGES[$COUNT]}" || -n "${FOUNDPACKAGESDESC[$COUNT]}" ]]; then
                            FOUNDPACKAGES[$COUNT]="$MOONPKGNAME"
                            FOUNDPACKAGESVERSION[$COUNT]="$MOONPKGVERSION"
                            FOUNDPACKAGESDESC[$COUNT]="$DESC"
                            if [ -d "$VEILERDBPATH/local/${FOUNDPACKAGES[$COUNT]}" ]; then
                                FOUNDPACKAGESINSTALLED[$COUNT]=" ${WHITE}||| ${YELLOW}Installed : ${WHITE}Yes${NC}"
                            else
                                FOUNDPACKAGESINSTALLED[$COUNT]=" ${WHITE}||| ${YELLOW}Installed : ${WHITE}No${NC}"
                            fi  
                            ((COUNT++))
                            unset MOONPKGNAME MOONPKGVERSION DESC
                        fi
                    fi
                done
            }
            SKIP=0
            DONEPACKAGES=()
            for((i=0; i < ${#FOUNDPACKAGES[@]} - 1; i++)){
                for((j=0; j < ${#DONEPACKAGES[@]}; j++)){
                    if [ "${DONEPACKAGES[$j]}" == "${FOUNDPACKAGES[$i]}" ]; then
                        SKIP=1
                    fi
                }
                if [ $SKIP -eq 1 ]; then SKIP=0; continue; fi
                echo -ne "${BLUE}${FOUNDPACKAGES[$i]} ${NC}"
                echo -ne "${GRAY}(${FOUNDPACKAGESVERSION[$i]})${NC}"
                echo -e "${FOUNDPACKAGESINSTALLED[$i]}"
                echo -e "\t${WHITE}${FOUNDPACKAGESDESC[$i]}${NC}"
                DONEPACKAGES+=( ${FOUNDPACKAGES[$i]} )
            } | more
        fi
    ;;
    sync)
        log_info imp "${YELLOW}|||${WHITE} Syncing package repo"
        if [ -d /var/lib/Veiler ]; then
            pushd /var/lib/Veiler &> /dev/null
            trap 'log_err "Could not sync repo!"' ERR
            set -e
            if [ -f db.tar.xz ]; then rm -f db.tar.xz; fi
            if [ "$VEILERQUIET" -eq 0 ]; then
                wget "https://github.com/ilovetrees242/Veiler/raw/refs/heads/main/db.tar.xz"
                tar -C "$VEILERDBPATH" --strip-components=1 -xvf db.tar.xz
            else
                wget -q --show-progress "https://github.com/ilovetrees242/Veiler/raw/refs/heads/main/db.tar.xz"
                tar -C "$VEILERDBPATH" --strip-components=1 -xf db.tar.xz
            fi
            set +e
            trap - ERR
            popd &> /dev/null
        else
            log_err "The package manager is not installed. Run the installation script again"
        fi
    ;;
    rmpkg)
        shift
        checkifroot
        if [ -z "$1" ]; then
            log_err "No package was provided!"
        fi
        PACKAGES=()
        for((i=1; i <= $#; i++)){
            PACKAGES[$((i-1))]=$(find ${VEILERCACHEPATH:-/var/cache/Veiler} -name "build-"${!i}"-*.*")
        }
        if [ ${#PACKAGES[@]} -eq 0 ]; then
            log_err "No occurences of the following packages could be found"
        fi
        log_info notice "The following occurences were found: "
        echo ${PACKAGES[@]}
        if [ $VEILERASK -eq 1 ]; then
            echo -ne "${WHITE}Are you sure you would like to ${RED}delete${WHITE} them?[y/n]: ${NC}"
            read -n 1
            if [ "$REPLY" == "y" ]; then
                true; echo
            elif [ "$REPLY" == "n" ]; then
                echo; exit 0
            fi
        fi
        trap 'log_err "Could not delete one or more occurences"' ERR
        for((i=0; i < ${#PACKAGES[@]}; i++)){
            if [ $VEILERQUIET -eq 1 ]; then
                rm -rf ${PACKAGES[$i]}
            else
                rm -rfv ${PACKAGES[$i]}
            fi
        }
        log_info notice "Successfully deleted all the occurences for: $@"
    ;;
    clearcache)
        if [ -n "$VEILERCACHEPATH" -a -d "$VEILERCACHEPATH" ]; then
            rm -rvf "${VEILERCACHEPATH:-/var/cache/Veiler}"/*
        fi
    ;;
    pkgs) 
        echo "$(find $VEILERDBPATH/local -type d | sed '1d' | wc -l )"
    ;;
    list) 
        printf "%s\n" "$(find $VEILERDBPATH/local -type d | sed '1d' | sed 's/.*local\///')"
    ;;
	*)
        if [ -z $1 ]; then 
            log_err "No action specified!"
        else
            log_err "Invalid action ${RED}$1${WHITE} specified!"
        fi
        $0 help
	;;
esac
